### ISSUE TITLE
gtfs - write of stop_code

### ISSUE THREAD

**Issue by prhod** [CanalTP/navitia_model#130]
The GTFS `stop_code` property should be read as an alternative `object_code` for the stop with the 
`object_system` set to `gtfs_stop_code`.

When writing the model as a GTFS, the `gtfs_stop_code` should be written in the stops.txt as a `stop_code`.
If there are several (due to GTFS merge for instance), juste take the first one for the moment :)

**Comment by TeXitoi** [comment]
This is possible:
```
codes: ["gtfs_stop_code": "foo", "gtfs_stop_code": "bar"]
```
So I think there is no problem with merging, just pass them all.

**Comment by prhod** [comment]
When reading and merging, you're right, but when writing a GTFS, we only have one slot and we have to choose.
