### ISSUE TITLE
Add type for date

### ISSUE THREAD

**Issue by datanel** [CanalTP/navitia_model#17]
as specified in https://github.com/CanalTP/navitia/blob/dev/documentation/ntfs/ntfs_fr.md#format-des-donn%C3%A9es

we should deserialize dates (format YYYYMMDD) and time (format HH:MM:SS) to an appropriate type

**Comment by TeXitoi** [comment]
Time is already done.

**Comment by TeXitoi** [comment]
https://docs.rs/chrono/0.4.0/chrono/naive/struct.NaiveDate.html looks like a good choice for the Date type.

**Comment by pbougue** [comment]
For the record (this should be added to comment somewhere also):
Using this Time structure seems better :
* only one u32 (vs. 2 for NaiveTime)
* naiveTime is 24h-bound
* it's not a "real" time, it's a duration interpreted like so : actual day at noon, minus 12h, plus this given duration
* as this is a important struct in this package (StopTimes are the most used) managing it closely seems smarter
