### ISSUE TITLE
Add the ability to read a zip 

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/navitia_model#170]
Hi here!

It would be quite nice to be able to directly read a `.zip` since it's usually the packaging of a GTFS.
In the same spirit, it might be helpful to read directly an url.

Would you be interested in such capabilities ?

It might need a bit of a refactor in the reader, I think we'll need to change all the utilities that takes a `AsRef<path::Path>` by  feeding them a `std::io::Read` (a bit like it's done in [gtfs-structure](https://github.com/rust-transit/gtfs-structure/blob/master/src/lib.rs#L308-L376).

As a side effect, would you be interested by a mean to have real time discussion ? It might be easier to exchange. We could set up a gitter channel or use IRC.

See you,
Antoine

**Comment by datanel** [comment]
Hi,

Yes we are interested and I have already begun that work with the possibility to load a zip or a directory.
```rust
trait ExploreDir<'a> {
    type Reader;
    type Err: Display;

    fn iter_path(&mut self) -> Vec<StdResult<PathBuf, Self::Err>>;
    fn open(&'a mut self, &Path) -> StdResult<Self::Reader, Self::Err>;
}
This should work for GTFS, NTFS, Netex.
```
but I had to give up for higher priority things.

I will see with the team for a gitter or IRC
