### ISSUE TITLE
Create helpers to ease unit testing

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/navitia_model#176]
This crate is well tested (good job :1st_place_medal: :sparkling_heart:  !) but mainly with integration tests, not unit tests.

For our crate https://github.com/etalab/transpo-rt we also started with integration tests, but I plan to add unit tests too.

To ease unit tests creation it would be nice to have a helper to create datasets (a bit like https://github.com/CanalTP/navitia/blob/dev/source/ed/build_helper.h#L216)

@Tristramg implemented [one in rust](https://github.com/Tristramg/csa-rust/blob/master/src/structures.rs#L52) for his CSA crate.

Would you be interested by such a feature ?

If so, since it's not a trivial problem, I think it would be nice to design at first the end use of such a builder in this issue.
Do you have an idea on how you want to write the tests ?

Note: I can't spend too much time on this, we should try to have a minimal design if you can't spend time on implementing it too.

**Comment by datanel** [comment]
What we note is that with unit tests we cannot cover every cases.
And it's easier to create fixtures than create model. 
But if a piece of code need to be unit tested and has a value, we "unit test" it.

**Comment by antoine-de** [comment]
Even if the subject does not seems to raise much intersset, I'd make a proposal.

What do you think ok:

```rust
 let model = ModelBuilder::default()
    .vj("toto", |vj_builder| {
        vj_builder
            .sa("A", "10:00:00".into(), "10:01:00".into())
            .make_sa("B", "11:00:00".into(), "11:01:00".into(), |mut sa| { // <-- a stop creation with total access to the object could be usefull for complex initialization
                sa.visible = false;
            })
    })
    // .vj(...)
    .build();
```

We could also go for something with less lambda (but then it cannot be chained):
```rust
let mut builder = ModelBuilder::default();

builder
    .vj("toto")
    .sa("A", "10:00:00".into(), "10:01:00".into())
    .make_sa("B", "11:00:00".into(), "11:01:00".into(), |mut sa| {
        sa.visible = false;
    });
    // builder.vj(...);
let model = builder.build();
```

what do you think ? do you see better/simplier api ?

**Comment by datanel** [comment]
why you cannot chain in the 2nd proposition if you always return a builder?

**Comment by antoine-de** [comment]
because `.vj(..)` will return a `VJBuilder` and not a builder (to mutate the current `vj`)

we could return a `Builder` and make `.sa(...)` work on the last `vj` but I'm not a fan of such implicit stuff

**Comment by antoine-de** [comment]
Some work still need to be done, but it's usable for the moment, I think we can close this
