### ISSUE TITLE
companies.txt: contributor_id attribute in data but not in spec

### ISSUE THREAD

**Issue by datanel** [CanalTP/navitia_model#19]
Some (all?) of `companies.txt` seems to have a `contributor_id` attribute not specified in the spec
https://github.com/CanalTP/navitia/blob/dev/documentation/ntfs/ntfs_fr.md#companiestxt-requis

**Comment by prhod** [comment]
as discussed, specs have been simplified https://github.com/CanalTP/navitia/pull/2282
Actual GTFS may have inconstancies until modification on production system is done.
