### ISSUE TITLE
[comment.txt] wrong fields interrupt bina abruptly

### ISSUE THREAD

**Issue by pbougue** [CanalTP/navitia_model#62]
Concerned file of NTFS:
https://github.com/CanalTP/navitia/blob/dev/documentation/ntfs/ntfs_fr.md#commentstxt-optionnel

2 problems:
* comment_type management
* comment_value/comment_name conflict

**comment_type**

* The value of this field is `standard` on at least one of our NTFS (stif dev). And the bina fails abruptly in mimir.
* The field is required in nav_model, while optional in the doc, in navitia2 (don't know about fusio)

I don't know what should be the behavior:
* enforce it
* ignore the field
* ignore the whole line
* ignore the whole file ( :trollface: )
* update NTFS doc
* patch fusio

**comment_value / comment_name conflict**

Probably an outdated documentation problem.
The field is named `comment_name` in navitia, and it's probably the same in fusio as we get it in NTFS files.
The field is named `comment_value` in the doc (and navitia_model sticked to that).

The simple correction would be to update doc and navitia_model.
Although the name is not super clear, so we might think of changing it in navitia and fusio. But as it is required, it would break retrocompat of files...

**comments.txt reading**

Anyway, on all that, my mind is that rejecting the whole bina for this comment file is too abrupt.

**Comment by pbougue** [comment]
This is probably also a more general error management policy issue, but at least here is an example to discuss that policy.

**Comment by pbougue** [comment]
Also this field is optionnal in the doc but required by nav-model :cry:

**Comment by datanel** [comment]
+1 for "update NTFS doc"

what do you think @prhod ?

**Comment by pbougue** [comment]
Updated the issue, as we had an other field problem.
@datanel : updating the doc is probably necessary, but I think we still need to build a policy for the way navitia_model handles it.

**Comment by TeXitoi** [comment]
fixed by #65

**Comment by TeXitoi** [comment]
Nop, not fixed
